# Schema for the configuration files of the URL Embed module.

url_embed.url_button.*:
  type: config_entity
  label: 'URL button config'
  mapping:
    label:
      type: label
      label: 'Name'
    id:
      type: string
      label: 'Machine name'
    button_icon_uuid:
      type: string
      label: 'Button image'
